import Header from '@/components/Header';
import Sidebar from '@/components/Sidebar';
import TopCards from '@/components/TopCards';
import Head from 'next/head';
import { useRouter } from 'next/router'
import React, { useEffect, useState } from 'react'
import { doc} from "firebase/firestore";
import { collection, getDocs } from "firebase/firestore";
import { app, db } from '@/FirebaseConfig';
import { FaCalendarTimes, FaExclamationCircle, FaFolder, FaPen, FaShoppingCart, FaTrash } from 'react-icons/fa';
const CategoryPage = () => {
  const router = useRouter();
  
  const { category } = router.query;// Access the dynamic parameter value

  const[products,setProducts]=useState([])

  useEffect(()=>{
    const dataRef = collection(db, "inventors");
      const ReadingTheDb=async()=>{
       
  
      const querySnapshot = await getDocs(collection(db, "inventory"));
      const productData = [];
      querySnapshot?.forEach((doc) => {
      productData?.push({...doc.data(),id:doc.id})
      });
      // setProducts(productData?productData:[])
      console.log(productData);
   
setProducts(productData.filter((products)=>products.categories== category
));
console.log(productData.filter((products)=>products.categories== category
));
  
   return () => {
    // Unsubscribe from the Firestore collection listener
   dataRef.onSnapshot(() => {});
  };

}

  ReadingTheDb()
 
},[])





  return (
    <div className='bg-gray-100 min-h-screen'>
    <Head>
      <title>Create Next App</title>
      <meta name='description' content='Generated by create next app' />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
    <Sidebar>
      <main className='bg-gray-100 h-[150vh] '>
        <Header />
        <TopCards />
        <div className='p-4 grid md:grid-cols-3 grid-cols-1 gap-4'>
          <h1>Category: {category}</h1>
        </div>
        <div class="flex flex-col">
  <div class="overflow-x-auto sm:mx-0.5 lg:mx-0.5">
    <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
      <div class="overflow-hidden">
      {products.length ==0 &&  <p className=' mb-4 text-red-700 font-[fantasy] text-lg font-bold bg-red-100 p-1'>Note: This section is empty </p>}
        <table class="min-w-full">
          
          <thead class="bg-gray-200 w-full border-b">
          <tr>
          
                <th scope="col" className="p-4">
                    <div className="flex items-center">
                  
                       S/N
                
                        {/* <input id="checkbox-all-search" type="checkbox" className="w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-800 dark:focus:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"/> */}
                        <label for="checkbox-all-search" className="sr-only">checkbox</label>
                    </div>
                </th>
                <th scope="col" className="px-6 py-3">
                    Product name
                </th>
                {/* <th scope="col" className="px-6 py-3">
                    C
                </th> */}
                <th scope="col" className="px-6 py-3">
                <div className="px-6   w-fit h-fit py-3 flex gap-3 justify-center items-center">
                    Category <FaFolder/>
                    </div>
                </th>
                <th scope="col" className="px-6 py-3">
                    Unit Price ₦
                </th>
                <th scope="col" className="px-6 py-3">
                <div className="px-6   w-fit h-fit py-3 flex gap-3 justify-center items-center">
                   In Stock <FaShoppingCart/>
                   </div>
                </th>
                <th scope="col"  className="px-6 py-3">
                    <div className="px-6  w-fit h-fit py-3 flex gap-3 justify-center items-center">
                        Expiring date <FaCalendarTimes/>
                    </div>
                   
                </th>
                <th scope="col" className="px-6 py-3">
                <div className="px-6 w-fit h-fit py-3 flex gap-3 justify-center items-center">
                   Total Price ₦
                   </div>
                </th>
             
                {/* <th scope="col" className="px-6 py-3">
            
                </th> */}
            </tr>
          </thead>
          <tbody className='w-full'>
           {products.length > 0? products.map((item,id)=>(

<tr class="bg-white border-b w-full text-center transition duration-300 ease-in-out hover:bg-gray-100">
<td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">   {id + 1}</td>
<td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
{item?.productName}
</td>
<td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
{item?.categories}
</td>
<td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
₦ {item?.costPrice}
</td>
<td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
{item?.quantity} X
</td>
<td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
{item?.day} 
</td>
<td class="text-sm text-gray-900 text-center font-light px-6 py-4 whitespace-nowrap">
{item?.quantity * item.costPrice} X
</td>

</tr>
           )) :
           <>
          
 <tr class="bg-white border-b w-full transition duration-300 ease-in-out hover:bg-gray-100">
           <td class="px-6 py-4 whitespace-nowrap text-center text-sm font-medium text-gray-900">   {1}</td>
           <td class="text-sm text-center  text-red-600 font-light px-6 py-4 whitespace-nowrap">
         EMPTY
           </td>
           <td class="text-sm  text-center text-red-600 font-light px-6 py-4 whitespace-nowrap">
           EMPTY
           </td>
           <td class="text-sm text-center  text-red-600 font-light px-6 py-4 whitespace-nowrap">
           ₦ 0
           </td>
           <td class="text-sm  text-center text-red-600 font-light px-6 py-4 whitespace-nowrap">
           EMPTY
           </td>
           <td class="text-sm text-center text-red-600 font-light px-6 py-4 whitespace-nowrap">
           EMPTY
           </td>
           <td class="text-sm text-center  text-red-600 font-light px-6 py-4 whitespace-nowrap">
           ₦ 0
           </td>
           
           </tr>
           </>
          }

          
            
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
        
      </main>
    </Sidebar>
  </div>
  )
}

export default CategoryPage
