import Navbar from '@/components/Navbar'
import React from 'react'
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { auth } from '@/FirebaseConfig';

const about = () => {
  return (
    <div>

      <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main style={{ backgroundImage: 'url(/office.png)' }} className='bg-gray-100 bg-no-repeat h-[150vh] '>

       <Navbar/>
       <div className=' flex  justify-center items-center gap-8'>
        <Image className=' h-[80vh] w-[50vw]' src={"/../public/F1.png"} alt="" height={250} width={250} />
        <div className=' flex flex-col gap-8'>
          {/* <h5 className=' text-[#51C9FF]'>Stand out of the crowd</h5> */}
          <h1 className='text-[#010D82]  font-bold'>About</h1>
          <p>This is a microservice  web-based inventory management software system developed to help Bells Consult Ltd improve inventory tracking.</p>
          <div className=' flex  items-center gap-5 '>
          {
              auth.currentUser ?  
          <Link href={'/home'}>
          <button className='py-4 px-8 w-fit hover:bg-blue-800/70  bg-[#010D82] text-white rounded-lg'>Get Started</button>
         </Link>
         :
         <>
          <button className='py-4 px-8 w-fit hover:bg-blue-800/70  bg-[#010D82] text-white rounded-lg'>Get Started</button>
        <button className='py-4 px-8 w-fit bg-blue-800/20 hover:bg-blue-800/70 hover:text-white   text-[#010D82] rounded-lg'>
         SignIn
          </button>
         </>
          }
       
          </div>
      

        </div>
       </div>
      </main>
    </>
    </div>
  )
}

export default about
