'use client'
import React, { useEffect, useState } from 'react'
import Header from '../components/Header';
import TopCards from '../components/TopCards';
import BarChart from '../components/BarChart';
import RecentOrders from '../components/RecentOrders';
import Head from 'next/head';
import Sidebar from '../components/Sidebar';
import withAuth from './withAuth';
import { collection,addDoc, getDocs } from "firebase/firestore"; 
import { auth, db } from '@/FirebaseConfig';


const admins = () => {
  const[admins,setAdmins]=useState([
   {
    name:'Dr Adegoke Micheal',
    phonenumber:'+234 805 792 7948',
    department:'Admin'
   },
   {
    name:'Olubowale Teniola Daniel',
    phonenumber:'+234 818 615 1624',
    department:'Admin'
   },


  ])
  const [users, setUsers] = useState([]);

  
  // useEffect(() => {
  //   const fetchData = async () => {
  //     const querySnapshot = await getDocs(collection(db, 'Admins'));

  //     querySnapshot.forEach((doc) => {
  //       const existingAdmins = [...admins];
  //       const adminData = doc.data();

  //       if (!existingAdmins.some((admin) => admin.name === adminData.name)) {
  //         existingAdmins.push(adminData);
  //         setAdmins(existingAdmins);
  //         addAdminToFirestore(adminData);
  //       }
  //   else{
  //     addAdminToFirestore(adminData);
  //   }
  //     });
  //   };

  //   fetchData();
  // }, []); // empty dependency array to run the effect only once
  // const addAdminToFirestore = async (admin) => {
  //   try {
  //     await addDoc(collection(db, 'Admins'), admin);
  //   } catch (error) {
  //     console.error('Error adding admin to Firestore:', error);
  //   }
  // };

  // Retrieve the admins collection and query the documents
   // Firebase authentication listener
//    useEffect(() => {
//    const unsubscribe = auth.onAuthStateChanged((user) => {
//     if (user) {
//       // User is signed in
//       setUsers((prevUsers) => [...prevUsers, user]);
//       console.log(users);
//     } else {
//       // User is signed out
//       setUsers([]);
//     }
//   });

//   // Clean up the listener on component unmount
//   return () => {
//     unsubscribe();
//   };
// }, []);



  return (
    <div>
       <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
<Sidebar>

     <main className='px-3  bg-gray-100 h-[150vh]  '>
        <Header />
        <TopCards />
       
        <div className='p-4 w-full grid  gap-2'>
             <h1 className=' text-[#010D82]  font-semibold'>Administrators </h1>
             <div class="flex flex-col">
  <div class="overflow-x-auto sm:mx-0.5 lg:mx-0.5">
    <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <table class="min-w-full">
          <thead class="bg-gray-200 border-b">
            <tr>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                #
              </th>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
               Admin Name
              </th>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
               Phone Number
              </th>
              <th scope="col" class="text-sm font-medium text-gray-900 px-6 py-4 text-left">
                Department
              </th>
            
            </tr>
          </thead>
          <tbody>
            {admins.map((admin,id)=>(

              <tr key={id} class="bg-white border-b transition duration-300 ease-in-out hover:bg-gray-100">
              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{id + 1}</td>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
              {admin.name}
              </td>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
                {admin.phonenumber}
              </td>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap">
              {admin.department ?  admin.department:'none'}
              </td>
             
            </tr>
            ))}
            
           
          
            
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
        </div>
      </main>
</Sidebar>
    </div>
  )
}

export default withAuth(admins)
