
import Header from '../components/Header';
import TopCards from '../components/TopCards';
import BarChart from '../components/BarChart';
import RecentOrders from '../components/RecentOrders';
import Head from 'next/head';
import Sidebar from '../components/Sidebar';
import withAuth from './withAuth';
import Image from 'next/image';
import Link from 'next/link';

const categories = () => {
  return (
    <div>
       <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
<Sidebar>

     <main className='px-3 bg-gray-100 h-[150vh]  '>
        <Header />
        <TopCards />
        <h1 className=' text-[#010D82]  font-semibold'>Categories </h1>
        <div className='p-4 grid md:grid-cols-2 grid-cols-1 gap-4'>
          <div className=' w-fit relativebg-[#51C9FF]  rounded-md'>
            <Link href="/categories/Drinks & Water">
          <Image className='  ' src={"/../public/g1.png"} alt="" height={150} width={320} />
             <p className=' text-center w-full font-semibold text-[1.4em] py-4 '> Drinks and Water</p>
           </Link>
          </div>
          <div className=' w-fit relativebg-[#51C9FF]  rounded-md'>
          <Link href="/categories/Snacks & Sweet">
          <Image className=' flex place-content-center ' src={"/../public/g2.png"} alt="" height={150} width={320} />
          <p className=' text-center w-full font-semibold text-[1.4em] py-4 '>Snacks & Sweet</p>
          </Link>
          </div>

          <div className=' w-fit relativebg-[#51C9FF]  rounded-md'>
          <Link href="/categories/Stationaries">
          <Image className=' flex place-content-center ' src={"/../public/g3.png"} alt="" height={150} width={320} />
          <p className=' text-center w-full font-semibold text-[1.4em] py-4 '>Stationaries</p>
          </Link>
          </div>
          <div className=' w-fit relativebg-[#51C9FF]  rounded-md'>
          <Link href="/categories/Provisions">
          <Image className=' flex place-content-center ' src={"/../public/g4.png"} alt="" height={150} width={320} />
          <p className=' text-center w-full font-semibold text-[1.4em] py-4 '> Provisions </p>
          </Link>
          </div>
          {/* <div className=' relativebg-[#51C9FF]  rounded-md'>
             <p className=' absolute bottom-1 text-center w-full'> drink and water</p>
           
          </div>
          <div className=' relativebg-[#51C9FF]  rounded-md'>
             <p className=' absolute bottom-1 text-center w-full'> drink and water</p>
           
          </div> */}
        </div>
      </main>
</Sidebar>
    </div>
  )
}

export default withAuth(categories)
