import Navbar from '@/components/Navbar'
import React from 'react'
import Head from 'next/head';
import Image from 'next/image';
import withAuth from './withAuth';

const contact = () => {
  return (
    <div>

    <>
    <Head>
      <title>Create Next App</title>
      <meta name='description' content='Generated by create next app' />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
    <main style={{ backgroundImage: 'url(/office.png)' }} className='bg-gray-100 bg-no-repeat h-[150vh] '>

     <Navbar/>
     <div className=' flex  justify-center text-[1.3em] font-semibold items-center gap-8'>
      <Image className=' h-[80vh] w-[50vw]' src={"/../public/F1.png"} alt="" height={250} width={250} />
      <div className=' flex flex-col gap-8'>
        {/* <h5 className=' text-[#51C9FF]'>Stand out of the crowd</h5> */}
        <h1 className='text-[#010D82]  font-bold'>Contact</h1>
        <p className=' w-[40em] flex flex-col gap-7'>
            <span>For more enquires you can contact:</span>
            
    <span>Bells Consult Ltd.: +234 8030 6815 65, +234 80 2850 8678</span>

    <span>Developer: tenidaniels@gmail.com.</span>

</p>
     
    

      </div>
     </div>
    </main>
  </>
  </div>
  )
}

export default contact
