
import Header from '../components/Header';
import TopCards from '../components/TopCards';
import BarChart from '../components/BarChart';
import RecentOrders from '../components/RecentOrders';
import Head from 'next/head';
import Sidebar from '../components/Sidebar';
import withAuth from './withAuth';
import { useState } from 'react';
import ProtectedRoute from '../components/ProtectedRoute';


const Home = () => {
  const [array,setArray]=useState([])
  return (

    <div className='bg-gray-100 min-h-screen'>

 <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <ProtectedRoute>


    
<Sidebar>

     <main className='bg-gray-100 h-[150vh] '>
        <Header />
        <TopCards setArray={setArray}/>
        <div className='p-4 grid md:grid-cols-3 grid-cols-1 gap-4'>
          <BarChart setArray={setArray} array={array} />
          {/* <RecentOrders /> */}
        </div>
      </main>
</Sidebar>
</ProtectedRoute>
     
  </div>
  )
}

export default withAuth(Home)
